### ISSUE TITLE
Support older hardware models

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#107]
The community would like to see older models also supported with the HA integration. We are currently making a firmware version for the older models to support the local server etc. and thus communication with HA.  There is no difference in the sensors, configuration etc that would impact the HA integration.

However these models will have a different model name:

DIY-PRO-4.3
DIY-PRO-3.7 and
DIY-BASIC-4.0

@joostlek Can we add these models and give them the exact same functionality like I-9PSL ?

**Comment by joostlek** [comment]
Currently we check if the model starts with `I` for enabling the display related entities and if the model contains an `L` for led bar entities, should both be added if the model contains `DIY` as well?

**Comment by airgradienthq** [comment]
@joostlek Yes we can add. 

Would that work?

DIY-PRO-I-4.3PS
DIY-PRO-I-3.7PS and
DIY-BASIC-I-4.0PS

none of the models has the LED bar but all models have a display.

**Comment by joostlek** [comment]
That would work after a small change yes

**Comment by airgradienthq** [comment]
Great. Then please implement that small change.

**Comment by joostlek** [comment]
Will do

**Comment by joostlek** [comment]
I am now also thinking, DIY already has I in it, so the model doesn't _have_ to change to make this work

**Comment by airgradienthq** [comment]
@joostlek Please use below names: I will also add them to the website.

DIY-PRO-I-4.3PS
DIY-PRO-I-3.7PS and
DIY-BASIC-I-4.0PS

**Comment by joostlek** [comment]
Fixed
