### ISSUE TITLE
Implement Correction formula for PM2.5 available on local server

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#113]
In the next firmware version we will implement a corrected PM2.5 value that will be a new property on the local-server.

[Documentation](https://github.com/airgradienthq/arduino/blob/master/docs/local-server.md) is already updated. 

New property is called:
pm02Compensated

I would suggest, Home Assistant checks if that new property is available and then uses that for the standard PM2.5. If not it should fall back to pm02 as currently implemented.

**Comment by joostlek** [comment]
Is this already implemented?
