### ISSUE TITLE
Configuration not becoming available after power cycle of monitor

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#121]
After a power cycle of the monitor, the sensors come up again automatically but configuration not:

![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/3d1b690a-503f-44ef-9143-296fba6d5d32)

Page Reload not fixes it.
Quick Reload not fixes it.

Only restart of Home Assistant fixes it:
![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/a8147fbb-8b27-4048-af18-9361ae4222ef)

**Comment by joostlek** [comment]
The polling interval for the configuration is 5 minutes and after every change we do (even though it's a local device, I don't think we change config that often that we should poll it a lot). I think if you wait a few more minutes it should work again.

Let me know if you think differently

**Comment by airgradienthq** [comment]
I think 5min is too long and if it does not create too much load I would go for at least 1min.
