### ISSUE TITLE
CO2 automatic baseline days do not get configuration

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#123]
It seems that the current set value for "CO2 automatic baseline calibration" is not set in the selector in Home Assistant.

See screenshot:
![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/aecea934-0c46-400f-9857-0bd156c4a267)

**Comment by joostlek** [comment]
Fixed when "1 day" was added
