### ISSUE TITLE
CO2 automatic baseline calibration misses "1 day"

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#124]
Please add "1 day" to the dropdown.
![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/213eb8d2-baa0-4878-a2ab-268b4372d89b)

Deafult is 8 days

To be consistent with our dashboard:
![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/bfd13acb-da92-487a-9255-bb8cc560235d)

**Comment by joostlek** [comment]
Oh didn't have that one in the screenshot I made, will add
