### ISSUE TITLE
Rename "CO2 automatic baseline calibration" selector

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#125]
To make it fit the selector and match our dashboard, I would suggest to rename to  "Set CO2 ABC period"

![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/0a9aa2d9-61b7-4880-9838-1b21a56a6b57)

**Comment by joostlek** [comment]
Yea my issue with this is that you have to know what ABC means to know what this means. On the website you have the header which tells what it means. That was my rationale for the naming

**Comment by airgradienthq** [comment]
Can you add a tooltip with the long name?
ABC is actually a pretty common abbreviation for CO2 sensors. It's important that it's clear its the period.
But you could also rename to "CO2 automatic baseline duration"

**Comment by joostlek** [comment]
We can't do a tooltip, but that new name sounds both explainable for people who don't know and is a little shorter. Will change!

**Comment by joostlek** [comment]
Fixed
