### ISSUE TITLE
Selectors show the property value but not the proper name.

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#126]
The selectors show the property value but not the proper name.
![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/ab070692-de85-47a4-aa01-81af1c893822)

Instead of the "c" should be "Celsius".

Same applies to all other selectors.

**Comment by joostlek** [comment]
And when you change it, does it go to the normal name?

**Comment by airgradienthq** [comment]
Strange. Now it's correct.
![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/b21cde3a-e18c-47d1-8317-6c04ee623c32)

I will do more testing.

**Comment by joostlek** [comment]
I'll also have a look at this one, this should not happen like this as "c" is translated in the frontend to "Celsius"
