### ISSUE TITLE
Change Order of Items in Configuration

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#131]
I would suggest to change the order of the configuration:

1) Put the Configuraton Source at the very top:

![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/dee4b105-6ba9-4e64-80c9-bb7002265ba9)

2) Put both learning offset next to each other
![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/69f234d9-6179-4b39-9f42-b66ad6d88476)
![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/4e033f80-ef81-4023-b310-e37f5c8b548c)

**Comment by joostlek** [comment]
Oh this is also alphabetical so this can be closed
