### ISSUE TITLE
Change order of air quality parameters

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#132]
I would rearrange (but keep existing names):

1. CO2
2. PM2.5
3. VOC Index
4. NOx Index
5. Temperature
6. Humidity
7. PM1
8. PM10
9. PM0.3
10. Raw VOC
11. Raw NOx

From 7. onwards is less important parameters.

![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/724a861b-6fff-4366-ba19-a91205d21d67)

**Comment by joostlek** [comment]
Its alphabetical, we can't change this. Users can change how they want this to appear on their dashboard themselves
