### ISSUE TITLE
Failed to Connect

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#166]
Raised at https://forum.airgradient.com/t/failed-to-connect-when-adding-to-home-assistant/2384

The AirGradients don’t get auto-discovered. The IP addresses I’m trying are definitely correct.

The only possible reason I can think of is that my HA server is on the 192.168.70 network, while my Wifi is 192.168.1. However, I can access the HA web interface from the Wifi on my laptop, so it seems that devices on both networks can see each other.

I’m quite new to HA, but I have successfully connected my Ikea Vindstyrka via Zigbee. Do I need to add anything (like MQTT) to HA to make it work?

<img width="422" alt="image" src="https://github.com/user-attachments/assets/5cab52fc-f884-48b7-a019-e4461e7c651f">

**Comment by graemian** [comment]
I'm the OP from the AirGradient forum. I figured out that the issue was my network. My Home Assistant couldn't connect back to the wifi network.

I changed my wifi router to bridge mode and it's all working fine now.

Sorry for the trouble.

**Comment by joostlek** [comment]
Awesome! Thanks for following up!
