### ISSUE TITLE
Implement OTA Update Notification

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#170]
We need to inform the user in Home Assistant if a new update is available for Home Assistant Certification. 

To do so, the following URL returns the latest version of the firmware.

http://hw.airgradient.com/sensors/airgradient:{{serial}}/generic/os/firmware 

This can be compared to the currently installed version.

If user allows connection to AirGradient cloud the updates will be installed automatically and no message required.

If not user does not allow connection to AirGradient, we can display a message:
"New firmware version available, please enable cloud connection for installation and then reboot monitor for installation."

@joostlek What do you think?

**Comment by joostlek** [comment]
Enable cloud connection = set the configuration source to cloud?

**Comment by joostlek** [comment]
This has been implemented and released in 2024.9
