### ISSUE TITLE
Missing Air Quality Parameters

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#20]
Currently I see:
![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/5223cc7e-23a8-46e2-9f96-3c522ea95304)

Missing are:
- rco2 (CO2 in ppt)
- pm003Count (The number of particles with a diameter beyond 0.3 microns in 1 deciliter of air)
- tvoc_raw (resistance from TVOC sensor)
- nox_raw (resistance from NOx sensor)
- boot (counter resets if device reboots)

**Comment by joostlek** [comment]
What would the unit of measurement be for the tvoc_raw and nox_raw?

**Comment by airgradienthq** [comment]
"ticks"

**Comment by joostlek** [comment]
And what's a good human readable name for the pm003? PM0.3?

**Comment by airgradienthq** [comment]
PM 0.3 Count

**Comment by joostlek** [comment]
I currently have co2 added as ppm as that's what we use in a device class. I just found out that the number is very low and that ppt would be more logical. If we can state our case and prove that this is a useful feature for all integrations, we could open an architectural proposal to add ppt as possible unit of measurement, allowing users to select between the two types and HA would automatically convert it for them

**Comment by airgradienthq** [comment]
Sorry my mistake. CO2 is ppm.

**Comment by joostlek** [comment]
Pushed
