### ISSUE TITLE
Icon Selection

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#21]
The [ESPhome integration from MalloArray](https://github.com/MallocArray/airgradient_esphome) has some good icon selection. Maybe we can use similar ones.

**Comment by joostlek** [comment]
I can't seem to find the icons in that repository.

For some icons (which mean exactly the same as the device class) I want to keep using the [device class](https://developers.home-assistant.io/docs/core/entity/sensor#available-device-classes) icon as icon. This ensures consistency between integrations and entities (something I have been doing to a lot of integrations recently)

**Comment by airgradienthq** [comment]
At the moment PM are shown with molecule icon. It would be better to use dust: 

mdi:weather-dust

For co2 you can use:
mdi:molecule-co2

**Comment by joostlek** [comment]
But again, for the PM0.1, PM2.5 and PM10 we use the device class icons. Maybe changing the default icon would be a nice thing, but I can't decide that on my own.

I am a bit pushing back here as this is what I also tell other people when reviewing their new integration or feature to maintain consistency.

**Comment by airgradienthq** [comment]
I understand your point of view, but I think that the current icon is not a good representation of PM. Other HA integrations like e.g. Airly also use other icon.

**Comment by joostlek** [comment]
Airly also uses the icons from the device classes. They only have one entity that had a custom icon, and that's the CAQI.

But like said, we can open a PR to change the default icon for that, but that also requires us to convince other maintainers that this is a better representation.

**Comment by airgradienthq** [comment]
Ok, I would suggest we go with the default at the moment.
