### ISSUE TITLE
Model in device response

### ISSUE THREAD

**Issue by joostlek** [airgradienthq/python-airgradient#23]
Currently we can only identify the model via the mDNS packet. But that means if someone sets up their device manually, it will look very odd, since we don't have a good name to give it except for the serial number to make it recognizable for the user. It would be helpful if we could receive the device info from the device itself so we don't have to fully rely on mDNS to give us that info.
<img width="432" alt="image" src="https://github.com/airgradienthq/python-airgradient/assets/7083755/8695bcc4-4ec9-40d9-bb8c-c8997157f1ec">

**Comment by airgradienthq** [comment]
So what do you suggest? A seperate endpoint on the monitor to GET the model?

**Comment by joostlek** [comment]
I think this is also a question for you guys about what you think is practical.

If adding this to the current measures endpoint is a performance impact, we can maybe have a separate endpoint for the device info (model, fw version, serial number). Because we only need that information once, since it's static (from the outside perspective).

The integration can work with any approach, but it's maybe just a discussion about what the best way to design the API is.
