### ISSUE TITLE
Hide missing parameter

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#24]
Not all models have all pollutants. Model O-1PP has no TVOC, NOx and CO2. Model O-1PPT lacks CO2. 
It would be good to hide the non existing pollutants then. Currently they are shown as unknown. 
![IMG_5200](https://github.com/airgradienthq/python-airgradient/assets/68736665/512f81b2-c6ce-44c9-b18b-3e2afa238e38)

**Comment by joostlek** [comment]
Hmm, the thing that's difficult, currently the values of these entities are set to None as that's the default. After booting the device (the moment my indoor monitor emits the zeroconf) the device isn't registering data yet, so I only receive some basic information (for an example of this checkout `tests/fixtures/(I think the file is called no_data).json`. so in those cases what it means is that it sets up with no entities and that's wrong.

But I like this idea in general, but I'm thinking on how to avoid the problem of creating no entities at all.

**Comment by airgradienthq** [comment]
What I mean is to hide the complete line because that pollutant is not part of that model.

**Comment by joostlek** [comment]
Yes, but there are several ways to approach this and that's or checking what data you have at setup and creating entities for that data. (So if the data is not None, we add the entity). Or checking via the model, but the latter way means you can't add new models easily and that always requires a library change because you need to tell the library that there is a new model with x data points.

**Comment by airgradienthq** [comment]
The model name basically defines which sensors part of the model and I don't expect it to change too much.  
So I think we can use model name.

We should support:
O-1PST (default) (PM, CO2, Tvoc, NOx, T, RH)
O-1PPT (2 channels PM, Tvoc, NOx, T, RH)
O-1PP (2 channels PM, T, RH)

**Comment by MallocArray** [comment]
> I don't expect it to change too much.

What about users to buy the upgrade parts to go from O-1PP to add a CO2, but may or may not also add the TVOC?  I had someone mention this just last week in regards to ESPHome changed required for that situation

**Comment by joostlek** [comment]
The integration only creates entities for the data it can find, so if that data isn't there, there are no entities created

**Comment by joostlek** [comment]
I think this is now solved
