### ISSUE TITLE
I-1PSL => I-9PSL

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/python-airgradient#26]
Model need to be called "**I**-9PSL"
![image](https://github.com/airgradienthq/python-airgradient/assets/68736665/3cba064b-b90f-4210-a070-149e7811cdc9)

**Comment by joostlek** [comment]
This is what is communicated to HA via the mDNS packet

**Comment by airgradienthq** [comment]
Ok. I will let the fw developer know.
