### ISSUE TITLE
Feature request: configuration option for data update frequency

### ISSUE THREAD

**Issue by aleyush** [airgradienthq/python-airgradient#279]
# Problem/Motivation

Now data is updated once a minute. That is great for most cases, but sometimes a more frequent update is needed.
For example, when automating ventilation unit on carbon dioxide sensor value it is good to consider not only the last value but also the trend. It is difficult to see the trend when the values are only once a minute.

## Expected behavior

An option to set data frequency update (integer seconds; or several options like "1 minute" (default), "15 seconds", "5 seconds")

## Actual behavior

No option, update is always once a minute.

**Comment by joostlek** [comment]
This is already possible using https://www.home-assistant.io/common-tasks/general/#defining-a-custom-polling-interval

**Comment by aleyush** [comment]
Thanks. Confirm it works.
